version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./backend.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=postgres
    ports:
    - "8000:8000"
    expose:
      - "8000"
    volumes:
    - ./:/app
    depends_on:
      - postgres
      - redis
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
