version: '3'

services:
  testapi:
    build:
      context: .
      dockerfile: ./backend.dockerfile
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_SERVER=testdb
      - POSTGRES_DB=test
    ports:
    - "8000:8000"
    expose:
      - "8000"
    volumes:
    - ./:/app
    depends_on:
      - testdb
      - redis
#    command: bash -c "alembic upgrade head && coverage report -m"

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  testdb:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
